[package]
org = "admin"
name = "test_structured_types"
version = "0.1.0"
distribution = "2201.12.0"

[[dependency]]
org="ballerinax"
name="np"
version="0.8.7"
repository="local"

[build-options]
observabilityIncluded = true
